### ISSUE TITLE
Some bugs and enhancement possibilities

### ISSUE THREAD

**Issue by mantasu** [mantasu/face-crop-plus#3]
# To-Do List

## Overview

Just a general to-do list and notes for the future update from **v1.0.3**.

## Bugs

* [x] Warning thrown if there are no landmarks for a specific filename in the case the landmarks are provided in prior
* [x] Error is thrown when `paddings` is tried to be accessed when landmarks are provided, i.e., missing initialization of `paddings = None`
* [x] STD Landmarks change when Cropper is instantiated a second time in a row, i.e., `STANDARD_LANDMARKS_5` is modified in `_init_landmarks_target`
* [x] Fix typos in documentation

## Behavior

* [x] Change default `padding` to `constant` (to avoid heads coming out of heads)
* [x] Change `enh_threshold` to `None` (to avoid unnecessary wasting time on enhancement)

## Enhancements

* [x] Custom description argument in `process_dir`
* [x] Utility to rename files to ASCII and shorten filenames (in-place and copy over)

**Comment by mantasu** [comment]
Closed with release [v1.1.0](https://github.com/mantasu/face-crop-plus/releases/tag/v1.1.0).
